version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: photostudio_db
    networks:
      - photostudio_net
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-photostudio}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-photostudio123}
      POSTGRES_DB: ${POSTGRES_DB:-photostudio}
    # чтобы не светить базу наружу
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-photostudio} -d ${POSTGRES_DB:-photostudio}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    image: ghcr.io/kuanyshmaral/photostudio-api:latest
    container_name: photostudio_api
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - photostudio_net
    ports:
      - "8090:8090"
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://${POSTGRES_USER:-photostudio}:${POSTGRES_PASSWORD:-photostudio123}@postgres:5432/${POSTGRES_DB:-photostudio}?sslmode=disable}
      PORT: ${PORT:-8090}
      ENV: ${ENV:-production}
      JWT_SECRET: ${JWT_SECRET:-change_me}
      DB_AUTO_MIGRATE: ${DB_AUTO_MIGRATE:-false}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  photostudio_net:
    name: photostudio_net
